server:
  port: 8001
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://root:123456@localhost:8001/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka-security-server8001
spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 123456