server:
  port: 8901
spring:
  cloud:
    config:
      server:
        git:
          uri: http://github.com/gotHot55/lcl-microservice-cloud.git
          clone-on-start: true #开启启动时直接从git获取配置
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true